---
- name: Install Server Monitor
  hosts: dev_infra
  become: true
  strategy: free
  roles:
    - { role: "monitorings/prometheus", tags: prometheus }
    - { role: "monitorings/node_exporter", tags: node_exporter }
    - { role: "monitorings/alertmanager", tags: alertmanager }
    - { role: "monitorings/blackbox_exporter", tags: blackbox_exporter }
    - { role: "monitorings/grafana", tags: grafana }
    - { role: "monitorings/nginx", tags: nginx }
    # - { role: "monitorings/zabbix_server", tags: zabbix_server }
    # - { role: "monitorings/zabbix_agent", tags: zabbix_agent }
