---
- name: Install Server Monitor
  hosts: dev_infra
  remote_user: "{{ remote_user }}"
  roles:
    - { role: "monitorings/prometheus/server", tags: prometheus }
    # - { role: "monitorings/zabbix/server", tags: prometheus }
