---

- name: install nginx
  dnf: name={{ item }} update_cache=yes state=present
  loop: [ php, php-mysqlnd, php-fpm, php-opcache, php-gd, php-xml, php-mbstring]

- name: Change user www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: 'user = apache'
    line: 'user = nginx'

- name: Change user www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: 'group = apache'
    line: 'group = nginx'

- name: Change user www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: ';listen.owner = nobody'
    line: 'listen.owner = nginx'

- name: Change user www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: 'listen.group = nobody'
    line: 'listen.group = nginx'

- name: Change user www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: ';listen.mode = 0660'
    line: 'listen.mode = 0660'

- name: Change user www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: 'listen.acl_users = apache'
    line: 'listen.acl_users = nginx'