---

- name: install nginx
  dnf: name={{ item }} update_cache=yes state=present
  loop: [ tar ]

- name: Download and Extract wordpress to /var/www/wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www
    remote_src: yes
    owner: nginx
    group: nginx

- name: Set wp-config.php file
  template:
    src: wp-config.php.j2 
    dest: /var/www/wordpress/wp-config.php
    owner: nginx
    group: nginx
    
- name: Creates database for WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  no_log: yes
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
