---
- name: Install MySQL-server
  dnf: name={{ item }} update_cache=yes state=present
  loop: [epel-release, mysql-server, python39, python39-devel, python39-pip, python3-PyMySQL]

- name: Install Required pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3

- name: set mysql config .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present

- name: Set the root password
  #no_log: true
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent

- name: be sure MySQL is running and enabled
  service:
    name: mysql
    state: started
    enabled: yes

