- name: restart blackbox.service
  systemd:
    name: blackbox.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart systemd-sysctl
  systemd:
    name: systemd-sysctl
    state: restarted