---
- name: set nginx repo
  copy:
    src: yum.nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: install nginx
  dnf: name=nginx update_cache=yes state=present

- name: remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Set wordpress.conf file for Nginx
  template:
    src: wordpressAlma.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf

- name: create conf.d.enabled directory
  file:
    state: directory
    dest: /etc/nginx/conf.d.enabled/

- name: create nginx link
  file:
    src: "/etc/nginx/conf.d/wordpress.conf"
    dest: "/etc/nginx/conf.d.enabled/wordpress.conf"
    state: link
  notify: restart nginx

- name: be sure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
