---
- name: Install LAMP
  hosts: devServers
  remote_user: root
  roles:
    - { role: "packages/lamp", tags: system }
    - { role: "stores/mysql", tags: mysql }
    #- { role: "webServers/apache", tags: apache }
    #- { role: "webServers/wordpress", tags: wordpress }
