---
- name: Install LAMP
  hosts: devServers
  remote_user: root
  roles:
    #- { role: "packages/php", tag: mysql } packages
    - { role: "stores/mysql", tags: mysql }
    #- { role: "webServers/apache", tags: apache }
    #- { role: "webServers/wordpress", tags: wordpress }