---
- name: Install all required packages for blackbox
  dnf: name={{ item }} update_cache=yes state=latest
  loop: ['wget', 'tar']

- name: Create 'blackbox' group
  group:
    name: blackbox
    state: present
    gid: 1004

- name: Create 'blackbox' user
  user:
    name: blackbox
    groups: blackbox
    state: present
    append: yes
    create_home: no

    #shell: /bin/false

- name: Download and Extract blackbox_exporter files to /tmp
  unarchive:
    src: https://github.com/prometheus/blackbox_exporter/releases/download/v0.20.0/blackbox_exporter-0.20.0.linux-amd64.tar.gz
    dest: /tmp
    validate_certs: no
    remote_src: yes

- name: Create blackbox directory
  file:
    path: /etc/blackbox
    state: directory
    owner: blackbox
    group: blackbox
    recurse: yes
    mode: 0755

- name: Add blackbox.yml config
  template:
    src: blackbox.yml.j2
    dest: /etc/blackbox/blackbox.yml
    owner: blackbox
    group: blackbox
    mode: 0644

- name: Copy blackbox binary file to /usr/local/bin/
  copy:
    src: /tmp/blackbox_exporter-0.20.0.linux-amd64/blackbox_exporter
    dest: /usr/local/bin/
    owner: blackbox
    group: blackbox
    remote_src: yes
    mode: +x

- name: Set permission for ping
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ping_group_range 1004 1004"
    state: present
  notify: restart systemd-sysctl

- name: Create systemd blackbox.service
  template:
    src: blackbox.service.j2
    dest: /etc/systemd/system/blackbox.service
  notify: restart blackbox.service
