---
- name: check Password
  debug:
    msg: 
    - "Password: {{ mysql_root_password }}"

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: 'localhost'
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true 
  tags: [ mysql, mysql-root ]

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]
