---
- name: Install all required packages for prometheus
  dnf: name={{ item }} update_cache=yes state=latest
  loop: ['wget', 'tar']

- name: Create 'prometheus' group
  group:
    name: prometheus
    state: present

- name: Create 'prometheus' user
  user:
    name: prometheus
    groups: prometheus
    state: present
    append: yes

- name: Create prometheus directories
  file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
  loop: ['/etc/prometheus', '/var/lib/prometheus']

- debug:
    msg: '{{ item }}'
  loop: ['/etc/prometheus', '/var/lib/prometheus']

- name: Download and Extract prometheus files to /tmp
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.34.0/prometheus-2.34.0.linux-amd64.tar.gz
    dest: /tmp
    validate_certs: no
    remote_src: yes


## check
- name: Copy files to prometheus directory \#1
  copy:
    src: /tmp/prometheus-2.34.0.linux-amd64/{{ item }}
    dest: /etc/prometheus/{{ item }}
    #src: "{{ item.src }}"
    #dest: "{{ item.dest }}"
    owner: prometheus
    group: prometheus
    directory_mode: yes
    mode: 775
    remote_src: yes
  #loop:
  #  - { src: '/tmp/prometheus-2.34.0.linux-amd64/prometheus.yml', dest: '/etc/prometheus/prometheus.yml' }
  #  - { src: '/tmp/prometheus-2.34.0.linux-amd64/console_libraries/', dest: '/etc/prometheus/console_libraries/' }
  #  - { src: '/tmp/prometheus-2.34.0.linux-amd64/consoles/', dest: '/etc/prometheus/consoles/' }
  loop: ['prometheus.yml', 'consoles/', 'console_libraries/']
  tags: files

- name: Copy files to prometheus directory \#2
  copy:
    src: /tmp/prometheus-2.34.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    remote_src: yes
  loop: ['prometheus', 'promtool']
  tags: files

- name: Create systemd prometheus.service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: start prometheus
