---
- name: Install prerequisites 
  yum: update_cache=yes state=latest
  tags: [ system ]

- name: Setting for Download php 5.6
  yum: name={{ item }} update_cache=yes state=present
  loop: [ 'http://rpms.remirepo.net/enterprise/remi-release-7.rpm', 'yum-utils' ]
  tags: [ system ]

- name: Disable remi-php54
  yum_repository: 
    name: remi-php54
    state: absent

- name: Enabled remi-php73
  yum_repository: 
    name: remi-php73
    state: absent
  notify: yum-clean-metadata

- name: Install LAMP Packages
  yum: name={{ item }} update_cache=yes state=latest
  loop: [ 'httpd', 'mysql-server', 'php', 'php-mysql', 'php-mbstring', 'php-mcrypt', 'php-devel', 'php-xml', 'php-gd' ]
  tags: [ system ]