---
- name: Download wordpress
  get_url: 
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress_latest.tar.gz

- name: Extract wordpress to /var/www/wordpress
    src: /tmp/wordpress_latest.tar.gz
    dest: /var/www/wordpress
    owner: www-data
    group: www-data

- name: Creates database for WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present