---
- name: Install all required packages for prometheus
  dnf: name={{ item }} update_cache=yes state=present
  loop: ['wget', 'tar']

- name: Install zabbix agent remote repo
  yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
    state: present

- name: Install zabbix agent
  dnf: name={{ item }} update_cache=yes state=present
  loop: [zabbix-agent, zabbix-sender]

- name: Create zabix-agent conf file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: start zabbix-agent