---
- name: Install all required packages for prometheus
  apt: name={{ item }} update_cache=yes state=latest
  loop: ['wget', 'tar']

- name: Install .deb package for zabbix agent
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb

- name: Install zabbix-agent
  apt:
    name: zabbix agent
    update_cache: yes
    state: present

- name: Create zabix-agent conf file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: start zabbix-agent