---
- name: Install all required packages for alertmanager
  dnf: name={{ item }} update_cache=yes state=latest
  loop: ['wget', 'tar']

- name: Download and Extract alertmanager files to /tmp
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
    dest: /tmp
    validate_certs: no
    remote_src: yes

- name: Create 'alertmanager' group
  group:
    name: alertmanager
    state: present

- name: Create 'alertmanager' user
  user:
    name: alertmanager
    groups: alertmanager
    state: present
    append: yes
    create_home: no
    shell: /bin/false

- name: Create alertmanager directories
  file:
    path: '{{ item }}'
    state: directory
    owner: alertmanager
    group: alertmanager
    recurse: yes
  loop: [/etc/alertmanager/, /var/lib/alertmanager/]

- name: Copy alertmanager binary file to /usr/local/bin/
  copy:
    src: /tmp/alertmanager-0.24.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    owner: alertmanager
    group: alertmanager
    remote_src: yes
    mode: +x
  loop: ['alertmanager', 'amtool']

- name: Add alertmanager.yml config yaml
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: 644

- name: Create systemd alertmanager.service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: restart alertmanager.service
