- name: install nginx
  apt: name=nginx update_cache=yes state=present

- name: Set wordpress.conf file for Nginx
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
    #owner: nginx
    #group: nginx

- name: Move default nginx file to back
  command: mv /etc/nginx/sites-available/default{,back}